# Generated by Django 5.2.5 on 2025-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inicio/')),
                ('texto', models.TextField()),
            ],
        ),
    ]
