# Generated by Django 5.2.5 on 2025-08-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenidoinicio',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='subtitulo',
        ),
    ]
