# Generated by Django 5.2.5 on 2025-08-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_texto_contenidoinicio_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenidoinicio',
            old_name='imagen',
            new_name='imagen1',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='titulo',
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='descripcion_img1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='descripcion_img2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='iframe_mapa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='imagen_manual',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='texto_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='titulo_galeria',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='url_manual',
            field=models.URLField(blank=True),
        ),
    ]
