# Generated by Django 5.2.5 on 2025-08-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_imagen_contenidoinicio_imagen1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='descripcion_img1',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='descripcion_img2',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='imagen2',
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.TextField(blank=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.contenidoinicio')),
            ],
        ),
    ]
