# Generated by Django 5.2.5 on 2025-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contenidoinicio_descripcion_img1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='imagen_manual',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterUniqueTogether(
            name='galleryimage',
            unique_together={('contenido', 'orden')},
        ),
    ]
